---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: management
  region: us-east-1

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    attachPolicyARNs:
    - "arn:aws:iam::${AWS_ACCOUNT_ID}:policy/AWSLoadBalancerControllerIAMPolicy"
    roleName: management-us-uest-1-aws-load-balancer-controller
