---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-int
  namespace: default
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-int
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-int
    spec:
      containers:
      - name: nginx
        image: nginx:1.23
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-int
  namespace: default
  labels:
    app: nginx-int
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-int
  type: LoadBalancer
