---
controller:
  replicaCount: 1

  ingressClassResource:
    enabled: true
    name: nginx-int
    controllerValue: "k8s.io/nginx-int"
  ingressClass: nginx-int
  ingressClassByName: true

  service:
    external:
      enabled: false
    internal:
      enabled: true
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: true
        service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
        service.beta.kubernetes.io/aws-load-balancer-internal: true
